[mypy]
python_version = 3.12

[mypy-celery]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-kombu]
ignore_missing_imports = True

[mypy-kombu.*]
ignore_missing_imports = True

[mypy-moviepy]
ignore_missing_imports = True

[mypy-moviepy.*]
ignore_missing_imports = True
